config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [ :show, :edit, :update, :destroy ]

  def index
    @flats = Flat.all
  end

  def show; end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)

    if @flat.save
      redirect_to @flat
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @flat.update(flat_params)
      redirect_to @flat
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @flat.destroy
    redirect_to @flat, status: :see_other
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for(@flat) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :description %>
  <%= f.input :number_of_guests %>
  <%= f.input :price_per_night %>

  <div class="d-flex gap-2">
    <%= f.submit "Create Flat", class: "btn btn-primary" %>

    <%= link_to "Cancel", flats_path, class: "btn btn-danger" %>
  </div>
<% end %>

app/views/flats/edit.html.erb
<div class="card bg-light p-4 w-50 mx-auto">
  <h1>Edit a Flat</h1>

  <%= render "form" %>
</div>

app/views/flats/index.html.erb
<h1>All our Flats</h1>

<p>All <%= @flats.count %> flats.</p>

<div class="row">
  <% @flats.each do |flat| %>
    <div class="col-md-4 mb-4">
      <div class="card shadow-sm">
        <div class="card-body bg-light">
          <h2 class="card-title fs-4"><%= flat.name %></h2>
          <p class="card-text"><%= flat.address %></p>

          <div class="d-flex gap-3">
            <div>
              <i class="fa-solid fa-user-group"></i>
              <span><%= flat.number_of_guests %></span>
            </div>
            <div>
              <i class="fa-solid fa-euro-sign"></i>
              <span><%= flat.price_per_night %></span>
            </div>
          </div>
        </div>

        <div class="card-body d-flex gap-3">
          <%= link_to "More info", flat_path(flat), class: "text-decoration-none"  %>
          <%= link_to "Edit", edit_flat_path(flat), class: "text-warning text-decoration-none" %>
          <%= link_to "Remove", flat_path(flat),
                        data: {turbo_method: :delete,
                        turbo_confirm: "Are you sure?"},
                        class: "text-danger text-decoration-none"
          %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/flats/new.html.erb
<div class="card bg-light p-4 w-50 mx-auto">
  <h1>Add a new Flat</h1>

  <%= simple_form_for(@flat) do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :number_of_guests %>
    <%= f.input :price_per_night %>

    <div class="d-flex gap-2">
      <%= f.submit "Create Flat", class: "btn btn-primary" %>

      <%= link_to "Cancel", flats_path, class: "btn btn-danger" %>
    </div>
  <% end %>
</div>

app/views/flats/show.html.erb
<div class="d-flex gap-4 mb-5">
  <%= link_to "Edit Flat", edit_flat_path(@flat), class: "btn btn-primary" %>
  <%= link_to "Remove", flat_path(@flat),
                data: {turbo_method: :delete,
                turbo_confirm: "Are you sure?"},
                class: "btn btn-danger"
  %>
</div>

<div class="d-flex gap-4">
  <section class="d-flex flex-column gap-2">
    <div class="card bg-light p-4 shadow-sm">
      <h1 class="card-title fs-2"><%= @flat.name %></h1>
      <p class="card-text"><%= @flat.address %></p>
    </div>

    <div class="card bg-light p-4 shadow-sm">
      <h2 class="fs-4">A bit more about this flat...</h2>
      <p class="card-text"><%= @flat.description %></p>
    </div>

    <div class="card bg-light p-4 shadow-sm">
      <h2 class="fs-4">Details</h2>
      <div class="d-flex gap-3">
        <div>
          <i class="fa-solid fa-user-group"></i>
          <span><%= @flat.number_of_guests %></span>
        </div>
        <div>
          <i class="fa-solid fa-euro-sign"></i>
          <span><%= @flat.price_per_night %></span>
        </div>
      </div>
    </div>
  </section>

  <section class="d-flex flex-column gap-3">
    <div class="card bg-light p-4 shadow-sm">
      <h3>Book this place!</h3>
      <form action="#" class="d-flex flex-column gap-2">
        <div class="d-flex">
          <label for="from_date" class="bg-secondary border bg-opacity-25 p-1 px-2">From:</label>
          <input type="text" id="from_date" name="from_date" class="form-control px-2" placeholder="26/02/2025">
        </div>

        <div class="d-flex">
          <label for="to_date" class="bg-secondary border bg-opacity-25 p-1 px-2">To:</label>
          <input type="text" id="to_date" name="to_date" class="form-control px-2" placeholder="28/02/2025">
        </div>

        <input type="submit" value="Book" class="btn btn-success">
      </form>

    </div>

    <div class="d-flex flex-row justify-content-between card bg-light p-4 shadow-sm">
      <span><strong>Share</strong></span>
      <div>
        <i class="fa-brands fa-square-facebook fs-4"></i>
        <i class="fa-brands fa-square-twitter fs-4"></i>
        <i class="fa-brands fa-square-pinterest fs-4"></i>
        <i class="fa-solid fa-square-envelope fs-4"></i>
      </div>
    </div>
  </section>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails Simple Airbnb" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav class="d-flex justify-content-between navbar navbar-expand-lg  navbar-light bg-light px-3">
      <%= link_to "Simple Airbnb", flats_path, class: "text-decoration-none navbar-brand" %>
      <%= link_to "Add Flat", new_flat_path, class: "btn btn-outline-primary my-2 my-sm-0 ms-2" %>
    </nav>

    <div class="container mt-3">
      <%= yield %>
    </div>
  </body>
</html>